-- ==============================================================================
-- STRUCTURE DE LA BASE DE DONNÉES - SIMULATEUR RÉSEAU TCP/IP
-- ==============================================================================
-- Ce script initialise le schéma relationnel vierge de l'application.
-- Il génère les 5 entités principales, strictement normalisées en 3FN, 
-- garantissant l'intégrité et le cloisonnement des données par utilisateur.
--
-- Utilisation : Exécutez ce script dans PostgreSQL pour préparer l'environnement 
-- de travail vierge avant le premier lancement du simulateur.
--
-- Développé par : Abasse ALI, Robin RIGAL et Ayyub BOUTAHIR.
-- ==============================================================================

-- Nettoyage préalable pour éviter les conflits lors de la réinitialisation
DROP TABLE IF EXISTS public.interface_reseau CASCADE;
DROP TABLE IF EXISTS public.route_statique CASCADE;
DROP TABLE IF EXISTS public.interface CASCADE;
DROP TABLE IF EXISTS public.equipement CASCADE;
DROP TABLE IF EXISTS public.reseau CASCADE;
DROP TABLE IF EXISTS public.utilisateur CASCADE;

-- ============================================================================
-- 1. CRÉATION DES TABLES ET SÉQUENCES
-- ============================================================================

-- --- Table : UTILISATEUR ---
CREATE TABLE public.utilisateur (
    idutilisateur integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    pseudo character varying(50) NOT NULL,
    motdepasse character varying(255) NOT NULL,
    CONSTRAINT pk_utilisateur PRIMARY KEY (idutilisateur)
);

-- --- Table : RESEAU ---
CREATE TABLE public.reseau (
    idreseau integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    adressereseau character varying(50) NOT NULL,
    masquecidr integer NOT NULL,
    x double precision DEFAULT 0,
    y double precision DEFAULT 0,
    CONSTRAINT pk_reseau PRIMARY KEY (idreseau)
);

-- --- Table : EQUIPEMENT ---
CREATE TABLE public.equipement (
    idequipement integer NOT NULL,
    nomequipement character varying(50) NOT NULL,
    typeequipement character varying(50) NOT NULL,
    idutilisateur integer NOT NULL,
    x double precision DEFAULT 0,
    y double precision DEFAULT 0,
    CONSTRAINT pk_equipement PRIMARY KEY (idequipement)
);

CREATE SEQUENCE public.equipement_idequipement_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.equipement_idequipement_seq OWNED BY public.equipement.idequipement;
ALTER TABLE ONLY public.equipement ALTER COLUMN idequipement SET DEFAULT nextval('public.equipement_idequipement_seq'::regclass);

-- --- Table : INTERFACE ---
CREATE TABLE public.interface (
    idinterface integer NOT NULL,
    adresseip character varying(15) NOT NULL,
    adressemac character varying(17) NOT NULL,
    idequipement integer NOT NULL,
    idreseau integer NOT NULL,
    CONSTRAINT pk_interface PRIMARY KEY (idinterface)
);

CREATE SEQUENCE public.interface_idinterface_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;

ALTER SEQUENCE public.interface_idinterface_seq OWNED BY public.interface.idinterface;
ALTER TABLE ONLY public.interface ALTER COLUMN idinterface SET DEFAULT nextval('public.interface_idinterface_seq'::regclass);

-- --- Table : ROUTE_STATIQUE ---
CREATE TABLE public.route_statique (
    idroute integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    reseaudestination character varying(50) NOT NULL,
    masquedestination character varying(50) NOT NULL,
    prochainsaut character varying(50) NOT NULL,
    idequipement integer NOT NULL,
    CONSTRAINT pk_route_statique PRIMARY KEY (idroute)
);

-- --- Table : INTERFACE_RESEAU (Table de support / d'extension) ---
CREATE TABLE public.interface_reseau (
    idinterface integer NOT NULL,
    idequipement integer NOT NULL,
    nominterface character varying(50) NOT NULL,
    adresseip character varying(50),
    adressemac character varying(50),
    idsousreseau character varying(100),
    masque character varying(50),
    passerelle character varying(50)
);

-- ============================================================================
-- 2. CONTRAINTES DE CLÉS ÉTRANGÈRES (FK)
-- ============================================================================

ALTER TABLE ONLY public.equipement
    ADD CONSTRAINT fk_equipement_utilisateur FOREIGN KEY (idutilisateur) REFERENCES public.utilisateur(idutilisateur) ON DELETE CASCADE;

ALTER TABLE ONLY public.interface
    ADD CONSTRAINT fk_interface_equipement FOREIGN KEY (idequipement) REFERENCES public.equipement(idequipement) ON DELETE CASCADE;

ALTER TABLE ONLY public.interface
    ADD CONSTRAINT fk_interface_reseau FOREIGN KEY (idreseau) REFERENCES public.reseau(idreseau) ON DELETE CASCADE;

ALTER TABLE ONLY public.route_statique
    ADD CONSTRAINT fk_route_equipement FOREIGN KEY (idequipement) REFERENCES public.equipement(idequipement) ON DELETE CASCADE;


-- ============================================================================
-- 3. INJECTION DU JEU DE DONNÉES (Topologie Complète de Simulation)
-- ============================================================================

-- 3.1. Création des Utilisateurs de test
INSERT INTO public.utilisateur (idutilisateur, pseudo, motdepasse) VALUES 
(1, 'Ayyub', 'password123'),
(2, 'Robin', 'securepass'),
(3, 'Abasse', 'admin2026');

-- 3.2. Création des Sous-Réseaux (avec coordonnées mémorisées)
INSERT INTO public.reseau (idreseau, adressereseau, masquecidr, x, y) VALUES 
(1, '192.168.1.0', 24, 400, 500),
(2, '192.168.2.0', 24, 300, 400),
(3, '192.168.3.0', 24, 600, 450),
(5, '192.168.5.0', 24, 500, 250);

-- 3.3. Création des Équipements (Hôtes et Routeurs liés à l'utilisateur 1 par défaut)
-- Coordonnées fixes pour éviter le désordre de Vis.js au rechargement
INSERT INTO public.equipement (idequipement, nomequipement, typeequipement, idutilisateur, x, y) VALUES 
(1, 'PC Robin', 'Hote', 1, 200, 550),
(2, 'PC Meud', 'Hote', 1, 450, 600),
(3, 'PC Ayyub', 'Hote', 1, 700, 550),
(10, 'Routeur 1', 'Routeur', 1, 300, 250),
(11, 'Routeur 2', 'Routeur', 1, 500, 150),
(12, 'Routeur 3', 'Routeur', 1, 600, 350);

-- 3.4. Création des Interfaces Réseau (Attribution des adresses IP et MAC)
INSERT INTO public.interface (idinterface, adresseip, adressemac, idequipement, idreseau) VALUES 
-- PC Hôtes
(1, '192.168.3.1', '00:00:0c:06:18:3a', 1, 3),   -- PC Robin sur Réseau .3
(2, '192.168.5.1', '02:60:9c:2e:b5:6b', 2, 5),   -- PC Meud sur Réseau .5
(3, '192.168.1.1', '00:00:0c:06:99:9a', 3, 1),   -- PC Ayyub sur Réseau .1

-- Interfaces Routeur 1
(101, '192.168.1.254', '00:00:0c:06:11:aa', 10, 1), -- Patte sur Réseau .1
(102, '192.168.2.254', '00:00:0c:06:11:bb', 10, 2), -- Patte sur Réseau .2

-- Interfaces Routeur 2
(201, '192.168.2.253', '00:00:0c:06:13:8a', 11, 2), -- Patte sur Réseau .2
(202, '192.168.5.254', '00:00:0c:06:20:8a', 11, 5), -- Patte sur Réseau .5

-- Interfaces Routeur 3
(301, '192.168.2.252', '02:64:8c:2e:b5:8b', 12, 2), -- Patte sur Réseau .2
(302, '192.168.3.254', '00:00:0c:06:13:3a', 12, 3); -- Patte sur Réseau .3

-- 3.5. Configuration des Tables de Routage Statiques (Scénario de test Multi-sauts)
INSERT INTO public.route_statique (reseaudestination, masquedestination, prochainsaut, idequipement) VALUES 
-- Routes sur Routeur 1
('192.168.3.0', '255.255.255.0', '192.168.2.252', 10),
('192.168.5.0', '255.255.255.0', '192.168.2.253', 10),

-- Routes sur Routeur 2
('192.168.1.0', '255.255.255.0', '192.168.2.254', 11),
('192.168.3.0', '255.255.255.0', '192.168.2.252', 11),

-- Routes sur Routeur 3
('192.168.1.0', '255.255.255.0', '192.168.2.254', 12),
('192.168.5.0', '255.255.255.0', '192.168.2.253', 12);
